### ISSUE TITLE
Add a dropdown-select to the Redis keys in RoutineForm

### ISSUE THREAD

**Issue by DorTruzman** [DorTruzman/PipeRTManager#8]
We should have a dropdown selector, like we have in the inner queues:
![image](https://user-images.githubusercontent.com/1783664/78408228-3b516b00-760f-11ea-8643-c539f8cc72eb.png).
It should contain all Redis queues for the user to choose (or create a new queue).
We can determine the type, as the parameter is sent from the server with "RedisIn" or "RedisOut" type (we should add it to the DataTypes in the server config file as well).

**Comment by tomerdayan168** [comment]
just to be sure, 
If I get from the server all of the Redis queues values, what the "create new queue" means ?

**Comment by DorTruzman** [comment]
> just to be sure,
> If I get from the server all of the Redis queues values, what the "create new queue" means ?

Sorry for the misunderstanding.
You are getting the TYPES from the server.
e.g:
![image](https://user-images.githubusercontent.com/1783664/78411054-077a4380-7617-11ea-9881-9e581695dc98.png)
You can use the type to determine the field type (whether you need to put a select there or not).
A similar implementation is already there for the QUEUE_READ and QUEUE_SEND types.

**Comment by tomerdayan168** [comment]
OK GOT IT !
